services:
  - type: web
    name: boston-house-pricing
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers=4 --bind 0.0.0.0:8000 app:app"
    envVars:
      - key: PORT
        value: 8000
        